# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- dev

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y libboost-all-dev
    gcc --version
    ls /usr/bin
- task: CMake@1
  inputs:
    workingDirectory: '.'
    cmakeArgs: '-DCMAKE_C_COMPILER=gcc-12 -D CMAKE_CXX_COMPILER=g++-12 .'
- task: CMake@1
  inputs:
    workingDirectory: '.'
    cmakeArgs: '--build . --verbose'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: './coretest'
    workingDirectory: 'coretest'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: './cputest'
    workingDirectory: 'cputest'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: './dasmtest'
    workingDirectory: 'dasmtest'
