# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y libboost-all-dev
    gcc --version
- task: CMake@1
  inputs:
    workingDirectory: '.'
    cmakeArgs: '-DBoost_INCLUDE_DIRS=/usr/include/boost -DCMAKE_C_COMPILER=clang-14 -D CMAKE_CXX_COMPILER=clang-14 .'
- task: CMake@1
  inputs:
    workingDirectory: '.'
    cmakeArgs: '--build . --verbose'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: './coretest'
    workingDirectory: 'coretest'
