#pragma once
#include <stddef.h>

namespace mc68000
{
    class instructions
    {
    public:
        static const unsigned short UNKNOWN = 0;
        static const unsigned short ABCD = 1;
        static const unsigned short ADD = 2;
        static const unsigned short ADDA = 3;
        static const unsigned short ADDI = 4;
        static const unsigned short ADDQ = 5;
        static const unsigned short ADDX = 6;
        static const unsigned short AND = 7;
        static const unsigned short ANDI = 8;
        static const unsigned short ANDI2CCR = 9;
        static const unsigned short ASL = 10;
        static const unsigned short ASR = 11;
        static const unsigned short BHI = 12;
        static const unsigned short BLS = 13;
        static const unsigned short BCC = 14;
        static const unsigned short BCS = 15;
        static const unsigned short BNE = 16;
        static const unsigned short BEQ = 17;
        static const unsigned short BVC = 18;
        static const unsigned short BVS = 19;
        static const unsigned short BPL = 20;
        static const unsigned short BMI = 21;
        static const unsigned short BGE = 22;
        static const unsigned short BLT = 23;
        static const unsigned short BGT = 24;
        static const unsigned short BLE = 25;
        static const unsigned short BCHG_R = 26;
        static const unsigned short BCHG_I = 27;
        static const unsigned short BCLR_R = 28;
        static const unsigned short BCLR_I = 29;
        static const unsigned short BRA = 30;
        static const unsigned short BSET_R = 31;
        static const unsigned short BSET_I = 32;
        static const unsigned short BSR = 33;
        static const unsigned short BTST_R = 34;
        static const unsigned short BTST_I = 35;
        static const unsigned short CHK = 36;
        static const unsigned short CLR = 37;
        static const unsigned short CMP = 38;
        static const unsigned short CMPA = 39;
        static const unsigned short CMPI = 40;
        static const unsigned short CMPM = 41;
        static const unsigned short DBCC = 42;
        static const unsigned short DIVS = 43;
        static const unsigned short DIVSL = 44;
        static const unsigned short DIVU = 45;
        static const unsigned short DIVUL = 46;
        static const unsigned short EOR = 47;
        static const unsigned short EORI = 48;
        static const unsigned short EORI2CCR = 49;
        static const unsigned short EXG = 50;
        static const unsigned short EXT = 51;
        static const unsigned short EXTB = 52;
        static const unsigned short ILLEGAL = 53;
        static const unsigned short JMP = 54;
        static const unsigned short JSR = 55;
        static const unsigned short LEA = 56;
        static const unsigned short LINK = 57;
        static const unsigned short LSL = 58;
        static const unsigned short LSR = 59;
        static const unsigned short MOVE = 60;
        static const unsigned short MOVEA = 61;
        static const unsigned short MOVECCR = 62;
        static const unsigned short MOVE2CCR = 63;
        static const unsigned short MOVESR = 64;
        static const unsigned short MOVEM = 65;
        static const unsigned short MOVEP = 66;
        static const unsigned short MOVEQ = 67;
        static const unsigned short MULS = 68;
        static const unsigned short MULU = 69;
        static const unsigned short NBCD = 70;
        static const unsigned short NEG = 71;
        static const unsigned short NEGX = 72;
        static const unsigned short NOP = 73;
        static const unsigned short NOT = 74;
        static const unsigned short OR = 75;
        static const unsigned short ORI = 76;
        static const unsigned short ORI2CCR = 77;
        static const unsigned short PEA = 78;
        static const unsigned short ROL = 79;
        static const unsigned short ROR = 80;
        static const unsigned short ROXL = 81;
        static const unsigned short ROXR = 82;
        static const unsigned short RTR = 83;
        static const unsigned short RTS = 84;
        static const unsigned short SBCD = 85;
        static const unsigned short SCC = 86;
        static const unsigned short SUB = 87;
        static const unsigned short SUBA = 88;
        static const unsigned short SUBI = 89;
        static const unsigned short SUBQ = 90;
        static const unsigned short SUBX = 91;
        static const unsigned short SWAP = 92;
        static const unsigned short TAS = 93;
        static const unsigned short TRAP = 94;
        static const unsigned short TRAPV = 95;
        static const unsigned short TST = 96;
        static const unsigned short UNLK = 97;

        static const unsigned short ANDI2SR = 98;

        static const size_t MAX_INSTRUCTIONS = 100;

        static const wchar_t* names[MAX_INSTRUCTIONS];

        instructions()
        {
            names[UNKNOWN] = L"UNKNOWN";
            names[ABCD] = L"ABCD";
            names[ADD] = L"ADD";
            names[ADDA] = L"ADDA";
            names[ADDI] = L"ADDI";
            names[ADDQ] = L"ADDQ";
            names[ADDX] = L"ADDX";
            names[AND] = L"AND";
            names[ANDI] = L"ANDI";
            names[ANDI2CCR] = L"ANDI2CCR";
            names[ASL] = L"ASL";
            names[ASR] = L"ASR";
            names[BHI] = L"BHI";
            names[BLS] = L"BLS";
            names[BCC] = L"BCC";
            names[BCS] = L"BCS";
            names[BNE] = L"BNE";
            names[BEQ] = L"BEQ";
            names[BVC] = L"BVC";
            names[BVS] = L"BVS";
            names[BPL] = L"BPL";
            names[BMI] = L"BMI";
            names[BGE] = L"BGE";
            names[BLT] = L"BLT";
            names[BGT] = L"BGT";
            names[BLE] = L"BLE";
            names[BCHG_R] = L"BCHG";
            names[BCHG_I] = L"BCHG";
            names[BCLR_R] = L"BCLR";
            names[BCLR_I] = L"BCLR";
            names[BRA] = L"BRA";
            names[BSET_R] = L"BSET";
            names[BSET_I] = L"BSET";
            names[BSR] = L"BSR";
            names[BTST_R] = L"BTST";
            names[BTST_I] = L"BTST";
            names[CHK] = L"CHK";
            names[CLR] = L"CLR";
            names[CMP] = L"CMP";
            names[CMPA] = L"CMPA";
            names[CMPI] = L"CMPI";
            names[CMPM] = L"CMPM";
            names[DBCC] = L"DBCC";
            names[DIVS] = L"DIVS";
            names[DIVSL] = L"DIVSL";
            names[DIVU] = L"DIVU";
            names[DIVUL] = L"DIVUL";
            names[EOR] = L"EOR";
            names[EORI] = L"EORI";
            names[EORI2CCR] = L"EORI2CCR";
            names[EXG] = L"EXG";
            names[EXT] = L"EXT";
            names[EXTB] = L"EXTB";
            names[ILLEGAL] = L"ILLEGAL";
            names[JMP] = L"JMP";
            names[JSR] = L"JSR";
            names[LEA] = L"LEA";
            names[LINK] = L"LINK";
            names[LSL] = L"LSL";
            names[LSR] = L"LSR";
            names[MOVE] = L"MOVE";
            names[MOVEA] = L"MOVEA";
            names[MOVECCR] = L"MOVECCR";
            names[MOVE2CCR] = L"MOVE2CCR";
            names[MOVESR] = L"MOVESR";
            names[MOVEM] = L"MOVEM";
            names[MOVEP] = L"MOVEP";
            names[MOVEQ] = L"MOVEQ";
            names[MULS] = L"MULS";
            names[MULU] = L"MULU";
            names[NBCD] = L"NBCD";
            names[NEG] = L"NEG";
            names[NEGX] = L"NEGX";
            names[NOP] = L"NOP";
            names[NOT] = L"NOT";
            names[OR] = L"OR";
            names[ORI] = L"ORI";
            names[ORI2CCR] = L"ORI2CCR";
            names[PEA] = L"PEA";
            names[ROL] = L"ROL";
            names[ROR] = L"ROR";
            names[ROXL] = L"ROXL";
            names[ROXR] = L"ROXR";
            names[RTR] = L"RTR";
            names[RTS] = L"RTS";
            names[SBCD] = L"SBCD";
            names[SCC] = L"SCC";
            names[SUB] = L"SUB";
            names[SUBA] = L"SUBA";
            names[SUBI] = L"SUBI";
            names[SUBQ] = L"SUBQ";
            names[SUBX] = L"SUBX";
            names[SWAP] = L"SWAP";
            names[TAS] = L"TAS";
            names[TRAP] = L"TRAP";
            names[TRAPV] = L"TRAPV";
            names[TST] = L"TST";
            names[UNLK] = L"UNLK";

            names[ANDI2SR] = L"ANDI2SR";
        }

    private:
        static instructions instance;
    };
}